### PR TITLE
Fix UI - Make Mobile First,remove navbar,fix dark mode color scheme,implement dark mode with local storage #9

### LINKED ISSUE #9: Fix UI - Make Mobile First,remove navbar,fix dark mode color scheme,implement dark mode with local storage
**Mobile-First Design:**
Refactor the UI components to ensure they are optimized for mobile devices first.
Test the design on various screen sizes to guarantee a seamless experience.

**Remove Navigation Bar**:
Identify the existing navigation bar and remove it from the layout.
Ensure that the application remains navigable without the navbar.

**Fix Dark Mode Color Scheme:**
Review the current dark mode color scheme and make necessary adjustments for better visibility and aesthetics.
Ensure that text and background colors provide sufficient contrast.
Implement Dark Mode with Local Storage:

Add functionality to toggle dark mode on and off.
Utilize local storage to save the user's preference for dark mode, ensuring that their choice persists across sessions.

### PR DESCRIPTION
**Pull request by darshitdudhaiya**
### Overview
This pull request introduces a significant overhaul of the UI structure by transitioning from standard HTML/CSS to a responsive mobile-first design using Tailwind CSS. The changes enhance the overall user experience, ensuring the application is visually appealing and functional across different devices.

### Key Changes

- Transition to Tailwind CSS:

All existing styles have been replaced with Tailwind utility classes, streamlining the styling process and ensuring consistency across the UI.

- Mobile-First Approach:

The layout and components have been optimized for mobile devices first, ensuring a seamless experience on smaller screens before adapting for larger displays.

- Light/Dark Mode Functionality:

Implemented a light/dark mode toggle that persists user preferences using localStorage.
The theme is automatically set based on the user's previous selection or their system preference.
      
- Improved UI Elements:

Fixed various UI elements for better usability and aesthetics.
Adjusted header and footer styles to enhance visibility and user interaction.
Enhanced link and button styles for better accessibility and user experience.

### Benefits

- Enhanced Responsiveness: The use of Tailwind CSS allows for better responsiveness, ensuring that components adapt gracefully to different screen sizes.
    
- User Preference Storage: By leveraging localStorage for theme preference, we ensure users retain their settings across sessions, improving overall user satisfaction.

- Cleaner Codebase: Transitioning to utility-first CSS reduces custom CSS and improves maintainability, making future updates easier to implement.

### Next Steps

- Test the implementation across various devices and browsers to ensure consistent functionality and appearance.

- Gather feedback from users regarding the new design and make any necessary adjustments.

### CODE REVIEW

**Comment by darshitdudhaiya** [comment]
@theajmalrazaq Please review my code and let me know if there are any changes needed.

**Review by theajmalrazaq — CHANGES_REQUESTED** [review]
@darshitdudhaiya  Please make the following adjustments to the pull request:

1. **Color Scheme Update**:
   - Update the entire color scheme to match the logo's colors for consistency across the interface.
   
2. **Re-add Favicons**:
   - Add back all favicons that were previously removed to ensure proper display on different browsers.
   
3. **Count and Price Inputs**:
   - Ensure the count and price input fields only appear when the "Count Now" button is clicked.
   
4. **Navbar Cleanup**:
   - Remove the following items from the navbar: Home, Statics, Settings, and History.
   
5. **Dark Mode Input Fields**:
   - Change the color of the input fields to match the dark mode theme. Right now, they are white, which breaks the theme's consistency.
   
6. **Delete Button Shape**:
   - Make the delete button square to match the shape of other buttons and maintain design consistency.
   
7. **Flash Messages**:
   - Add flash messages to notify users when actions are successfully completed:
     - On adding quantity: "Successfully added."
     - On deleting an item: "Successfully deleted."
     - On clearing all items: "Successfully cleared."

---

Once these changes are implemented, the pull request will be ready for final review. Thank you!

**Comment by darshitdudhaiya** [comment]
@theajmalrazaq Thank you so much for reviewing my code! I'll report back to you after making the changes you suggested.

**Comment by darshitdudhaiya** [comment]
@theajmalrazaq Please check now. I think everything is alright now.

**Review by theajmalrazaq — APPROVED** [review]
## Thank you, @darshitdudhaiya! 🎉

We appreciate your contributions to **Liquidia**. You've done an excellent job, and we are grateful for your efforts. 🙌

Wishing you a **Happy Hacktoberfest**! 🎃🎈

**Pull request merged**
